package com.bgdude.app.pump

import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.ServiceConnection
import android.os.IBinder
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.EventChannel

/**
 * Bridges the Flutter engine to [PumpService]. Two channels:
 *   * The Pigeon-generated [PumpHostApi] (command/request surface) — implemented by
 *     [PumpHostApiImpl], which forwards to the bound service.
 *   * An [EventChannel] `bgdude/pump_events` that streams snapshot + connection-state
 *     JSON to Dart at CGM cadence.
 *
 * NOTE: `PumpApi.g.kt` (with `PumpHostApi.setUp` and the `PumpFlutterApi` proxy) is
 * generated by Pigeon from `pigeons/pump_api.dart`. Run `dart run pigeon` before build.
 */
class PumpBridge(
    private val context: Context,
    private val engine: FlutterEngine,
) : PumpService.Callbacks {

    private var service: PumpService? = null
    private var eventSink: EventChannel.EventSink? = null
    private lateinit var hostApiImpl: PumpHostApiImpl

    private val connection = object : ServiceConnection {
        override fun onServiceConnected(name: ComponentName?, binder: IBinder?) {
            val svc = (binder as PumpService.LocalBinder).service()
            svc.callbacks = this@PumpBridge
            service = svc
            hostApiImpl.bind(svc)
        }

        override fun onServiceDisconnected(name: ComponentName?) {
            service = null
            hostApiImpl.bind(null)
        }
    }

    fun attach() {
        hostApiImpl = PumpHostApiImpl(context)
        // Generated: PumpHostApi.setUp(messenger, hostApiImpl)
        PumpHostApiRegistrar.register(engine.dartExecutor.binaryMessenger, hostApiImpl)

        EventChannel(engine.dartExecutor.binaryMessenger, EVENT_CHANNEL)
            .setStreamHandler(object : EventChannel.StreamHandler {
                override fun onListen(arguments: Any?, events: EventChannel.EventSink?) {
                    eventSink = events
                }

                override fun onCancel(arguments: Any?) {
                    eventSink = null
                }
            })

        // Start + bind the foreground service.
        val intent = Intent(context, PumpService::class.java)
        context.startForegroundService(intent)
        context.bindService(intent, connection, Context.BIND_AUTO_CREATE)
    }

    fun detach() {
        try {
            context.unbindService(connection)
        } catch (_: IllegalArgumentException) {
        }
        service?.callbacks = null
        eventSink = null
    }

    // --- PumpService.Callbacks: push to Dart ---

    override fun onState(state: NativeConnectionState) {
        eventSink?.success(
            mapOf(
                "kind" to "state",
                "stage" to state.stage.name,
                "model" to state.model.name,
                "pumpName" to state.pumpName,
                "jpakeProgress" to state.jpakeProgress,
                "error" to state.errorMessage,
            )
        )
    }

    override fun onSnapshot(json: String) {
        eventSink?.success(mapOf("kind" to "snapshot", "json" to json))
    }

    override fun onPairingCodeRequired(type: PairingCodeType) {
        eventSink?.success(mapOf("kind" to "pairingCode", "type" to type.name))
    }

    override fun onCriticalError(message: String) {
        eventSink?.success(mapOf("kind" to "criticalError", "message" to message))
    }

    companion object {
        private const val EVENT_CHANNEL = "bgdude/pump_events"
    }
}
