package com.bgdude.app.pump

import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.content.ServiceConnection
import android.os.IBinder
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MethodChannel

/**
 * Bridges the Flutter engine to [PumpService]. Two channels:
 *   * The Pigeon-generated [PumpHostApi] (command/request surface) — implemented by
 *     [PumpHostApiImpl], which forwards to the bound service.
 *   * An [EventChannel] `bgdude/pump_events` that streams snapshot + connection-state
 *     JSON to Dart at CGM cadence.
 *
 * NOTE: `PumpApi.g.kt` (with `PumpHostApi.setUp` and the `PumpFlutterApi` proxy) is
 * generated by Pigeon from `pigeons/pump_api.dart`. Run `dart run pigeon` before build.
 */
class PumpBridge(
    private val context: Context,
    private val engine: FlutterEngine,
) : PumpService.Callbacks {

    private var service: PumpService? = null
    private var eventSink: EventChannel.EventSink? = null
    private lateinit var hostApiImpl: PumpHostApiImpl

    private val connection = object : ServiceConnection {
        override fun onServiceConnected(name: ComponentName?, binder: IBinder?) {
            val svc = (binder as PumpService.LocalBinder).service()
            svc.callbacks = this@PumpBridge
            service = svc
            hostApiImpl.bind(svc)
        }

        override fun onServiceDisconnected(name: ComponentName?) {
            service = null
            hostApiImpl.bind(null)
        }
    }

    fun attach() {
        hostApiImpl = PumpHostApiImpl(context)

        // Command surface: a plain MethodChannel matching Dart's PumpClient. All
        // commands are read-only requests; there is no control/bolus path.
        MethodChannel(engine.dartExecutor.binaryMessenger, COMMAND_CHANNEL)
            .setMethodCallHandler { call, result ->
                when (call.method) {
                    "startScan" -> {
                        // The user grants Bluetooth permissions before scanning; make
                        // sure the service is foregrounded now that it's allowed.
                        ensureForegroundStarted()
                        hostApiImpl.startScan(call.argument("macFilter")) {
                            result.success(null)
                        }
                    }
                    "stopScan" -> hostApiImpl.stopScan { result.success(null) }
                    "requestStatus" ->
                        hostApiImpl.requestStatusJson { r ->
                            result.success(r.getOrNull())
                        }
                    "submitPairingCode" -> {
                        val code = call.argument<String>("code") ?: ""
                        val type = if (call.argument<String>("type") == "LONG_16CHAR") {
                            PairingCodeType.LONG_16CHAR
                        } else {
                            PairingCodeType.SHORT_6CHAR
                        }
                        hostApiImpl.submitPairingCode(code, type) { result.success(null) }
                    }
                    "unpair" -> hostApiImpl.unpair { result.success(null) }
                    "fetchHistory" ->
                        // Drain whatever history-log entries the service has decoded so
                        // far (best-effort; pumpx2's decode is partial and unvalidated
                        // on hardware). The Dart importer dedups via a high-water mark.
                        result.success(service?.fetchHistory() ?: emptyList<Map<String, Any?>>())
                    "requestProfile" -> {
                        service?.requestProfile()
                        result.success(null)
                    }
                    else -> result.notImplemented()
                }
            }

        EventChannel(engine.dartExecutor.binaryMessenger, EVENT_CHANNEL)
            .setStreamHandler(object : EventChannel.StreamHandler {
                override fun onListen(arguments: Any?, events: EventChannel.EventSink?) {
                    eventSink = events
                }

                override fun onCancel(arguments: Any?) {
                    eventSink = null
                }
            })

        // Always bind (creates the service without foregrounding); only *start* it as
        // a foreground service when the Bluetooth runtime permission is granted —
        // Android 14+ hard-rejects a connectedDevice FGS without it (fresh installs).
        val intent = Intent(context, PumpService::class.java)
        if (PumpService.hasBluetoothPermission(context)) {
            context.startForegroundService(intent)
        }
        context.bindService(intent, connection, Context.BIND_AUTO_CREATE)
    }

    /** Re-attempt the foreground start (call after the permission flow completes). */
    private fun ensureForegroundStarted() {
        if (PumpService.hasBluetoothPermission(context)) {
            context.startForegroundService(Intent(context, PumpService::class.java))
        }
    }

    fun detach() {
        try {
            context.unbindService(connection)
        } catch (_: IllegalArgumentException) {
        }
        service?.callbacks = null
        eventSink = null
    }

    // --- PumpService.Callbacks: push to Dart ---

    override fun onState(state: NativeConnectionState) {
        eventSink?.success(
            mapOf(
                "kind" to "state",
                "stage" to state.stage.name,
                "model" to state.model.name,
                "pumpName" to state.pumpName,
                "jpakeProgress" to state.jpakeProgress,
                "error" to state.errorMessage,
            )
        )
    }

    override fun onSnapshot(json: String) {
        eventSink?.success(mapOf("kind" to "snapshot", "json" to json))
    }

    override fun onPairingCodeRequired(type: PairingCodeType) {
        eventSink?.success(mapOf("kind" to "pairingCode", "type" to type.name))
    }

    override fun onCriticalError(message: String) {
        eventSink?.success(mapOf("kind" to "criticalError", "message" to message))
    }

    override fun onTherapyProfile(json: String) {
        eventSink?.success(mapOf("kind" to "profile", "json" to json))
    }

    companion object {
        private const val EVENT_CHANNEL = "bgdude/pump_events"
        private const val COMMAND_CHANNEL = "bgdude/pump_commands"
    }
}
