/// Pump history-log decode coverage (issue #94).
///
/// Generated from the pumpx2 jar and `PumpHistoryMapper`; kept in step with
/// `doc/pump-history-coverage.md` by `HistoryLogCoverageTest` (Kotlin, checks the
/// markdown against the jar) and `history_log_coverage_test.dart` (checks this list
/// against the same markdown). Neither the number nor the list can drift silently.
library;

/// One pump history-log event type and whether bgdude turns it into therapy data.
class HistoryLogType {
  const HistoryLogType(this.name, {required this.decoded});

  final String name;
  final bool decoded;
}

const List<HistoryLogType> historyLogTypes = [
  HistoryLogType('AAExerciseChoiceChangeHistoryLog', decoded: false),
  HistoryLogType('AAExerciseTimeChangeHistoryLog', decoded: false),
  HistoryLogType('AATdiEstChangeHistoryLog', decoded: false),
  HistoryLogType('AaAutoBolusRejectedHistoryLog', decoded: false),
  HistoryLogType('AaDeliveryStatusChangeHistoryLog', decoded: false),
  HistoryLogType('AaEnableSettingChangeHistoryLog', decoded: false),
  HistoryLogType('AaSleepScheduleChangeHistoryLog', decoded: false),
  HistoryLogType('AaTdiSettingChangeHistoryLog', decoded: false),
  HistoryLogType('AaWeightSettingChangeHistoryLog', decoded: false),
  HistoryLogType('AlarmAckHistoryLog', decoded: false),
  HistoryLogType('AlarmActivatedHistoryLog', decoded: true),
  HistoryLogType('AlarmClearedHistoryLog', decoded: false),
  HistoryLogType('AlertAckHistoryLog', decoded: false),
  HistoryLogType('AlertActivatedHistoryLog', decoded: true),
  HistoryLogType('AlertClearedHistoryLog', decoded: false),
  HistoryLogType('ArmInitHistoryLog', decoded: false),
  HistoryLogType('BGHistoryLog', decoded: false),
  HistoryLogType('BasalDeliveryHistoryLog', decoded: false),
  HistoryLogType('BasalIqSettingsChangeHistoryLog', decoded: false),
  HistoryLogType('BasalRateChangeHistoryLog', decoded: true),
  HistoryLogType('BolexActivatedHistoryLog', decoded: false),
  HistoryLogType('BolexCompletedHistoryLog', decoded: false),
  HistoryLogType('BolusActivatedHistoryLog', decoded: false),
  HistoryLogType('BolusCompletedHistoryLog', decoded: true),
  HistoryLogType('BolusDeliveryHistoryLog', decoded: false),
  HistoryLogType('BolusRequestedMsg1HistoryLog', decoded: false),
  HistoryLogType('BolusRequestedMsg2HistoryLog', decoded: false),
  HistoryLogType('BolusRequestedMsg3HistoryLog', decoded: false),
  HistoryLogType('CannulaFilledHistoryLog', decoded: true),
  HistoryLogType('CarbEnteredHistoryLog', decoded: true),
  HistoryLogType('CartridgeFilledHistoryLog', decoded: true),
  HistoryLogType('CartridgeInsertedHistoryLog', decoded: false),
  HistoryLogType('CartridgeRemovedHistoryLog', decoded: false),
  HistoryLogType('CgmAlertAckDexHistoryLog', decoded: false),
  HistoryLogType('CgmAlertAckHistoryLog', decoded: false),
  HistoryLogType('CgmAlertActivatedDexHistoryLog', decoded: false),
  HistoryLogType('CgmAlertActivatedFsl2HistoryLog', decoded: false),
  HistoryLogType('CgmAlertActivatedHistoryLog', decoded: false),
  HistoryLogType('CgmAlertClearedDexHistoryLog', decoded: false),
  HistoryLogType('CgmAlertClearedFsl2HistoryLog', decoded: false),
  HistoryLogType('CgmAlertClearedHistoryLog', decoded: false),
  HistoryLogType('CgmAnnuSettingsHistoryLog', decoded: false),
  HistoryLogType('CgmBleCalibrationEvtG7HistoryLog', decoded: false),
  HistoryLogType('CgmCalibrationG7HistoryLog', decoded: false),
  HistoryLogType('CgmCalibrationGxHistoryLog', decoded: false),
  HistoryLogType('CgmCalibrationHistoryLog', decoded: false),
  HistoryLogType('CgmDataFsl2HistoryLog', decoded: false),
  HistoryLogType('CgmDataFsl3HistoryLog', decoded: false),
  HistoryLogType('CgmDataGxHistoryLog', decoded: true),
  HistoryLogType('CgmDataSampleHistoryLog', decoded: false),
  HistoryLogType('CgmFraSettingsHistoryLog', decoded: false),
  HistoryLogType('CgmHgaSettingsHistoryLog', decoded: false),
  HistoryLogType('CgmInactiveG7HistoryLog', decoded: false),
  HistoryLogType('CgmInactiveGxHistoryLog', decoded: false),
  HistoryLogType('CgmJoinSessionFsl2HistoryLog', decoded: false),
  HistoryLogType('CgmJoinSessionFsl3HistoryLog', decoded: false),
  HistoryLogType('CgmJoinSessionG7HistoryLog', decoded: false),
  HistoryLogType('CgmJoinSessionHistoryLog', decoded: false),
  HistoryLogType('CgmLgaSettingsHistoryLog', decoded: false),
  HistoryLogType('CgmOorSettingsHistoryLog', decoded: false),
  HistoryLogType('CgmPairingCodeG7HistoryLog', decoded: false),
  HistoryLogType('CgmRejoinSessionHistoryLog', decoded: false),
  HistoryLogType('CgmRraSettingsHistoryLog', decoded: false),
  HistoryLogType('CgmSensorTypeChangeHistoryLog', decoded: false),
  HistoryLogType('CgmSessionTypeChangeHistoryLog', decoded: false),
  HistoryLogType('CgmStartSensorReqG7HistoryLog', decoded: false),
  HistoryLogType('CgmStartSessionFsl2HistoryLog', decoded: false),
  HistoryLogType('CgmStartSessionHistoryLog', decoded: false),
  HistoryLogType('CgmStartSessionReqGxHistoryLog', decoded: false),
  HistoryLogType('CgmStopSessionFsl2HistoryLog', decoded: false),
  HistoryLogType('CgmStopSessionFsl3HistoryLog', decoded: false),
  HistoryLogType('CgmStopSessionG7HistoryLog', decoded: false),
  HistoryLogType('CgmStopSessionHistoryLog', decoded: false),
  HistoryLogType('CgmStopSessionMsg1HistoryLog', decoded: false),
  HistoryLogType('CgmStopSessionMsg2HistoryLog', decoded: false),
  HistoryLogType('CgmStopSessionReqG7HistoryLog', decoded: false),
  HistoryLogType('CgmStopSessionReqGxHistoryLog', decoded: false),
  HistoryLogType('CgmTransmitterIdGxHistoryLog', decoded: false),
  HistoryLogType('CgmTransmitterIdHistoryLog', decoded: false),
  HistoryLogType('CgmTransmitterVersionGxHistoryLog', decoded: false),
  HistoryLogType('CgmUnexpectedGeAlertHistoryLog', decoded: false),
  HistoryLogType('ConfirmCartridgeFilledHistoryLog', decoded: false),
  HistoryLogType('ControlIQPcmChangeHistoryLog', decoded: false),
  HistoryLogType('ControlIQUserModeChangeHistoryLog', decoded: false),
  HistoryLogType('CorrectionDeclinedHistoryLog', decoded: false),
  HistoryLogType('DailyBasalHistoryLog', decoded: false),
  HistoryLogType('DailyStatusHistoryLog', decoded: false),
  HistoryLogType('DataLogCorruptionHistoryLog', decoded: false),
  HistoryLogType('DateChangeHistoryLog', decoded: false),
  HistoryLogType('DexcomG6CGMHistoryLog', decoded: false),
  HistoryLogType('DexcomG7CGMHistoryLog', decoded: false),
  HistoryLogType('FactoryResetHistoryLog', decoded: false),
  HistoryLogType('FillEstimateFinalHistoryLog', decoded: false),
  HistoryLogType('HistoryLog', decoded: false),
  HistoryLogType('HypoMinimizerResumeHistoryLog', decoded: false),
  HistoryLogType('HypoMinimizerSuspendHistoryLog', decoded: false),
  HistoryLogType('IdpActionHistoryLog', decoded: false),
  HistoryLogType('IdpActionMsg2HistoryLog', decoded: false),
  HistoryLogType('IdpBolusHistoryLog', decoded: false),
  HistoryLogType('IdpListHistoryLog', decoded: false),
  HistoryLogType('IdpTimeDependentSegmentHistoryLog', decoded: false),
  HistoryLogType('LogErasedHistoryLog', decoded: false),
  HistoryLogType('MalfunctionAckHistoryLog', decoded: false),
  HistoryLogType('MalfunctionHistoryLog', decoded: false),
  HistoryLogType('NewDayHistoryLog', decoded: false),
  HistoryLogType('ParamChangeGlobalSettingsHistoryLog', decoded: false),
  HistoryLogType('ParamChangePumpSettingsHistoryLog', decoded: false),
  HistoryLogType('ParamChangeRemSettingsHistoryLog', decoded: false),
  HistoryLogType('ParamChangeReminderHistoryLog', decoded: false),
  HistoryLogType('PlgsPeriodicHistoryLog', decoded: false),
  HistoryLogType('PrimeInprocessHistoryLog', decoded: false),
  HistoryLogType('PumpingResumedHistoryLog', decoded: false),
  HistoryLogType('PumpingSuspendedHistoryLog', decoded: false),
  HistoryLogType('ReminderActivatedHistoryLog', decoded: false),
  HistoryLogType('ReminderDismissedHistoryLog', decoded: false),
  HistoryLogType('ReminderSnoozedHistoryLog', decoded: false),
  HistoryLogType('ShelfModeHistoryLog', decoded: false),
  HistoryLogType('SnoozeActivatedHistoryLog', decoded: false),
  HistoryLogType('TempRateActivatedHistoryLog', decoded: false),
  HistoryLogType('TempRateCompletedHistoryLog', decoded: false),
  HistoryLogType('TimeChangedHistoryLog', decoded: false),
  HistoryLogType('TipsErrorHistoryLog', decoded: false),
  HistoryLogType('TipscReqPrimeCannulaHistoryLog', decoded: false),
  HistoryLogType('TubingFilledHistoryLog', decoded: false),
  HistoryLogType('UnknownHistoryLog', decoded: false),
  HistoryLogType('UpdateStatusHistoryLog', decoded: false),
  HistoryLogType('UsbConnectedHistoryLog', decoded: false),
  HistoryLogType('UsbDisconnectedHistoryLog', decoded: false),
  HistoryLogType('UsbEnumeratedHistoryLog', decoded: false),
  HistoryLogType('VersionInfoHistoryLog', decoded: false),
  HistoryLogType('VersionsAHistoryLog', decoded: false),
  HistoryLogType('WumpCartridgeFilledHistoryLog', decoded: false),
  HistoryLogType('WumpCartridgeRemovedHistoryLog', decoded: false),
  HistoryLogType('WumpOcclusionDebugHistoryLog', decoded: false),
];

/// How many of the pump's event types bgdude decodes.
int get decodedHistoryLogCount =>
    historyLogTypes.where((t) => t.decoded).length;
